PlayerProfilesPath: /home/sftp_minecraft/RMTests/
player:
  baseMana: 20
  baseHP: 20
  ActionBarDelay: 40
  HealthUpdateDelay: 20
  AutoSaveDelay: 4800

XP_For_Level:
  1: 75
  2: 125
  3: 200
  4: 300
  5: 500
  6: 750
  7: 1000
  8: 1500
  9: 2125
  10: 3500
  11: 5000
  12: 7500
  13: 10000
  14: 15000
  15: 22500
  16: 32500
  17: 50000
  18: 75000
  19: 125000
  20: 200000
  21: 300000
  22: 400000
  23: 500000
  24: 600000
  25: 700000
  26: 800000
  27: 900000
  28: 1000000
  29: 1150000
  30: 1300000
  31: 1450000
  32: 1600000
  33: 1750000
  34: 1900000
  35: 2050000
  36: 2200000
  37: 2350000
  38: 2500000
  39: 2650000
  40: 2800000
  41: 3000000
  42: 3200000
  43: 3400000
  44: 3600000
  45: 3800000
  46: 4000000
  47: 4250000
  48: 4500000
  49: 4750000
  50: 5000000
  51: 5250000
  52: 5500000
  53: 5750000
  54: 6000000
  55: 6250000
  56: 6500000
  57: 6750000
  58: 7000000
  59: 7250000
  60: 7500000

mining:
  STONE: 1
  COBBLESTONE: 1
  GRANITE: 1.2
  DIORITE: 1.2
  ANDESITE: 1.2
  COBBLED_DEEPSLATE: 2
  COAL_ORE: 5
  COPPER_ORE: 6
  IRON_ORE: 6
  GOLD_ORE: 8
  GLOWSTONE: 9
  LAPIS_ORE: 8
  DIAMOND_ORE: 14
  EMERALD_ORE: 12
  ANCIENT_DEBRIS: 50
  REDSTONE_ORE: 8
  OBSIDIAN: 22
  ICE: 0.3
foraging:
  OAK_LOG: 6
  SPRUCE_LOG: 6
  BIRCH_LOG: 6.5
  JUNGLE_LOG: 7
  ACACIA_LOG: 6
  DARK_OAK_LOG: 6
farmingcrops:
  WHEAT: 4
  POTATOES: 4
  CARROTS: 4
  BEETROOTS: 4
farmingblocks:
  SUGAR_CANE: 2.5
  CACTUS: 2
  MELON: 4
  PUMPKIN: 5



lvlrewards:
  combat:
    1:
      strength: 4
      critchance: 0.5
    2:
      strength: 8
      critchance: 1
    3:
      strength: 12
      critchance: 1.5
    4:
      strength: 16
      critchance: 2
    5:
      strength: 20
      critchance: 2.5
    6:
      strength: 24
      critchance: 3
    7:
      strength: 28
      critchance: 3.5
    8:
      strength: 32
      critchance: 4
    9:
      strength: 36
      critchance: 4.5
    10:
      strength: 40
      critchance: 5
    11:
      strength: 44
      critchance: 5.5
    12:
      strength: 48
      critchance: 6
    13:
      strength: 52
      critchance: 6.5
    14:
      strength: 56
      critchance: 7
    15:
      strength: 60
      critchance: 7.5
    16:
      strength: 64
      critchance: 8
    17:
      strength: 68
      critchance: 8.5
    18:
      strength: 72
      critchance: 9
    19:
      strength: 76
      critchance: 9.5
    20:
      strength: 80
      critchance: 10
    21:
      strength: 84
      critchance: 10.5
    22:
      strength: 88
      critchance: 11
    23:
      strength: 92
      critchance: 11.5
    24:
      strength: 96
      critchance: 12
    25:
      strength: 100
      critchance: 12.5
    26:
      strength: 104
      critchance: 13
    27:
      strength: 108
      critchance: 13.5
    28:
      strength: 112
      critchance: 14
    29:
      strength: 116
      critchance: 14.5
    30:
      strength: 120
      critchance: 15
    31:
      strength: 124
      critchance: 15.5
    32:
      strength: 128
      critchance: 16
    33:
      strength: 132
      critchance: 16.5
    34:
      strength: 136
      critchance: 17
    35:
      strength: 140
      critchance: 17.5
    36:
      strength: 144
      critchance: 18
    37:
      strength: 148
      critchance: 18.5
    38:
      strength: 152
      critchance: 19
    39:
      strength: 156
      critchance: 19.5
    40:
      strength: 160
      critchance: 20
    41:
      strength: 164
      critchance: 20.5
    42:
      strength: 168
      critchance: 21
    43:
      strength: 172
      critchance: 21.5
    44:
      strength: 176
      critchance: 22
    45:
      strength: 180
      critchance: 22.5
    46:
      strength: 184
      critchance: 23
    47:
      strength: 188
      critchance: 23.5
    48:
      strength: 192
      critchance: 24
    49:
      strength: 196
      critchance: 24.5
    50:
      strength: 200
      critchance: 25
    51:
      strength: 201
      critchance: 25.5
    52:
      strength: 202
      critchance: 26
    53:
      strength: 203
      critchance: 26.5
    54:
      strength: 204
      critchance: 27
    55:
      strength: 205
      critchance: 27.5
    56:
      strength: 206
      critchance: 28
    57:
      strength: 207
      critchance: 28.5
    58:
      strength: 208
      critchance: 29
    59:
      strength: 209
      critchance: 29.5
    60:
      strength: 210
      critchance: 30
  mining:
    1:
      defense: 1
      oremultiplychance: 4
    2:
      defense: 2
      oremultiplychance: 8
    3:
      defense: 3
      oremultiplychance: 12
    4:
      defense: 4
      oremultiplychance: 16
    5:
      defense: 5
      oremultiplychance: 20
    6:
      defense: 6
      oremultiplychance: 24
    7:
      defense: 7
      oremultiplychance: 28
    8:
      defense: 8
      oremultiplychance: 32
    9:
      defense: 9
      oremultiplychance: 36
    10:
      defense: 10
      oremultiplychance: 40
    11:
      defense: 11
      oremultiplychance: 44
    12:
      defense: 12
      oremultiplychance: 48
    13:
      defense: 13
      oremultiplychance: 52
    14:
      defense: 14
      oremultiplychance: 56
    15:
      defense: 15
      oremultiplychance: 60
    16:
      defense: 16
      oremultiplychance: 64
    17:
      defense: 17
      oremultiplychance: 68
    18:
      defense: 18
      oremultiplychance: 72
    19:
      defense: 19
      oremultiplychance: 76
    20:
      defense: 20
      oremultiplychance: 80
    21:
      defense: 22
      oremultiplychance: 84
    22:
      defense: 24
      oremultiplychance: 88
    23:
      defense: 26
      oremultiplychance: 92
    24:
      defense: 28
      oremultiplychance: 96
    25:
      defense: 30
      oremultiplychance: 100
    26:
      defense: 32
      oremultiplychance: 104
    27:
      defense: 34
      oremultiplychance: 108
    28:
      defense: 36
      oremultiplychance: 112
    29:
      defense: 38
      oremultiplychance: 116
    30:
      defense: 40
      oremultiplychance: 120
    31:
      defense: 42
      oremultiplychance: 124
    32:
      defense: 44
      oremultiplychance: 128
    33:
      defense: 46
      oremultiplychance: 132
    34:
      defense: 48
      oremultiplychance: 136
    35:
      defense: 50
      oremultiplychance: 140
    36:
      defense: 52
      oremultiplychance: 144
    37:
      defense: 54
      oremultiplychance: 148
    38:
      defense: 56
      oremultiplychance: 152
    39:
      defense: 58
      oremultiplychance: 156
    40:
      defense: 60
      oremultiplychance: 160
    41:
      defense: 62
      oremultiplychance: 164
    42:
      defense: 64
      oremultiplychance: 168
    43:
      defense: 66
      oremultiplychance: 172
    44:
      defense: 68
      oremultiplychance: 176
    45:
      defense: 70
      oremultiplychance: 180
    46:
      defense: 72
      oremultiplychance: 184
    47:
      defense: 74
      oremultiplychance: 188
    48:
      defense: 76
      oremultiplychance: 192
    49:
      defense: 78
      oremultiplychance: 196
    50:
      defense: 80
      oremultiplychance: 200
    51:
      defense: 82
      oremultiplychance: 204
    52:
      defense: 84
      oremultiplychance: 208
    53:
      defense: 86
      oremultiplychance: 212
    54:
      defense: 88
      oremultiplychance: 216
    55:
      defense: 90
      oremultiplychance: 220
    56:
      defense: 92
      oremultiplychance: 224
    57:
      defense: 94
      oremultiplychance: 228
    58:
      defense: 96
      oremultiplychance: 234
    59:
      defense: 98
      oremultiplychance: 240
    60:
      defense: 100
      oremultiplychance: 250

