name: RM_Core
version: '0.2'
main: com.ruinsmc.RM_Core
api-version: 1.18
authors: [ hihoffff ]
depend:
  - NBTAPI
commands:
  admin:
    usage: /admin give item {Название предмета}
  menu:
    usage: /menu (открывает главное меню)
  skills:
    usage: /skills (открывает меню навыков)
